### ISSUE TITLE
Suite reference tree view/hierarchy/breadcrumbs

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-doc#158]
It would be useful to have a way of seeing all the config items in https://cylc.github.io/cylc-doc/8.0a2/html/reference/config/suite.html in a tree view in a sidebar, to make it easier to find items and see what they fit in the config hierarchy (i.e. what sections a particular setting needs to be under). Another option could be to have a breadcrumb at each item that shows where it falls in the hierarchy.

**Comment by oliver-sanders** [comment]
This is a long-running gripe I have with Sphinx (we have the same issue with the Rose docs) hence I didn't do anything in cylc-sphinx-extensions at the time in the hope that there might be a nicer solution.

Anything documented with a Sphinx domain (e.g. configuration items within the `cylc` Sphinx domain) aren't registered in the document model (pages, titles, subheadings, etc) because they are orthogonal to it. Unfortunately this means they cannot appear in the sidebar which is very very annoying.

I looked back when I did the Rose docs and couldn't find a nice simple way to get these entities into the document model, however, that was Sphinx1 and we are now on Sphinx3 so things may have changed. Could be worth a search, see if there is a switch or something, we can't be the only people annoyed by this.

Alternatively, if there is some way to insert an invisible section marker that would do the trick, just add it into the autodocumenter in cylc-sphinx-extensions. (do avoid hacking the rtd-theme though).

A scroll-spy type solution (displaying the breadcrum in an fixed position HTML element at the top of the page) would be very nice, but that definitely would involve hacking the sphinx-rtd-theme.

Final fallback is just to add the full configuration namespace for each configuration (i.e. above the default), if it's all we can do, fine.

**Comment by MetRonnie** [comment]
> I looked back when I did the Rose docs and couldn't find a nice simple way to get these entities into the document model, however, that was Sphinx1 and we are now on Sphinx3 so things may have changed. Could be worth a search, see if there is a switch or something, we can't be the only people annoyed by this.

I spent the morning trying to look into this, but I didn't have much luck

**Comment by MetRonnie** [comment]
Note: the id of each item is the same as its "breadcrumb" (e.g. `flow.cylc[scheduler][events]handlers`), so when you click the permalink icon it shows up in the address bar. It sort of does the job actually, but not necessarily noticeable

**Comment by oliver-sanders** [comment]
I think we really need this, however, getting fancy navigation working with Sphinx is way out of scope at the moment.

The simplest quickest fix is just to add the name of the configuration into the configuration docs - https://github.com/cylc/cylc-sphinx-extensions/issues/49
