### ISSUE TITLE
Retire the term "task jobs"

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#352]
We define "tasks" and "jobs" as well as explaining the relationship between them.

The undefined term "task jobs" appears throughout the docs (and beyond). When I was starting out this term confused me, it's unclear how the term "job" differs from "task job". If we mean jobs we should just say jobs.

This term made a little more sense in Cylc 7 where tasks and jobs were more convoluted.

Propose removing this term, replacing it with either task or job as applicable.

**Comment by hjoliver** [comment]
The original intent of the term was to indicate task ownership, just like it does for other terms such as: 
- task definition
- task environment section
- task job script
- (e.t.c.)
- task job 
 
I think that makes some sense in that light, but if others find it confusing I don't particularly mind reverting to plain old *job*.

It wasn't because "tasks and jobs were more convoluted" in Cylc 7 - they weren't really, as far as the scheduler was concerned,  it's just that the Cylc 7 GUI did not make the distinction.

**Comment by oliver-sanders** [comment]
Kinda get that, but why task-jobs and not cycle-tasks or workflow-cycles or workflow//cycle/task/job, seems clearer to pull these concepts apart to me.

(Would also like to consider breaking the task-job mapping in the future as part of sub-workflows and auto-batched job submission.)

Propose:

* task job -> job [1]
* task job script -> job script [1]
* task job log -> job log [1]
* task job environment -> job environment

> [1] Currently defined in the glossary

**Comment by hjoliver** [comment]
Yep, I'm good with that.

**Comment by MetRonnie** [comment]
I don't think this is rightfully closed, waiting on #528?
