### ISSUE TITLE
Migration guide: optional outputs

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-doc#484]
A page in the detailed description of major changes that gives an example of a Cylc7 branched graph that works in back-compat mode but fails once `suite.rc` has been renamed to `flow.cylc`, and how to upgrade to optional outputs

**Comment by oliver-sanders** [comment]
Due to the validation of optional outputs, almost all branched workflows will fail Cylc 8 validation (post-upgrade) until upgraded to use optional outputs (because Cylc knows that `:success` and `:fail` are mutually exclusive).

There is a worked example in the [suicide trigger section](https://cylc.github.io/cylc-doc/latest/html/7-to-8/major-changes/suicide-triggers.html) which shows how to upgrade from suicide triggers to optional outputs.

That page links to the [graph branching](https://cylc.github.io/cylc-doc/latest/html/user-guide/writing-workflows/scheduling.html#graph-branching) section which outlines common patterns with optional outputs.
