### ISSUE TITLE
Slight error in the xtrigger documentation around uuid?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-doc#546]
I was looking at https://cylc.github.io/cylc-doc/latest/html/user-guide/writing-workflows/external-triggers.html#custom-trigger-functions and noticed mention of `uuid` and `suite_uuid`. The `suite_uuid` mentions it is deprecated and to use `uuid_str`. I'm not sure which is correct, but I'm guessing `uuid` should be `uuid_str` or `uuid_str` should be `uuid`?

![image](https://user-images.githubusercontent.com/15375218/193731328-d3cf19c7-488e-4d85-a4ce-a4517b5e094b.png)

**Comment by MetRonnie** [comment]
Thanks for reporting this. It turns out that list was being autogenerated from the wrong part of the source code. The correct list looks like this (will be corrected in the next docs release):

![image](https://user-images.githubusercontent.com/61982285/199051233-a1d21641-25e0-4dc5-9465-9b094b67162f.png)
